clusterName: "cluster-stag"

image:
  repository: "apache/rocketmq"
  tag: "4.9.4"

broker:
  size:
    master: 1
    replica: 1

  persistence:
    enabled: true
    size: 10Gi
    storageClass: "cbs"

nameserver:
  replicaCount: 1

dashboard:
  enabled: true
  replicaCount: 1

  ingress:
    enabled: false
    className: "nginx"
    hosts:
      - host: rocketmq.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    #tls:
    #  - secretName: example-com-tls
    #    hosts:
    #      - rocketmq.example.com
