clusterName: "rocketmq-cluster-a"

image:
  repository: "apache/rocketmq"
  pullPolicy: IfNotPresent
  tag: "4.9.4"

# Configuration for the broker
broker:
  # -- Number of master broker and number of replica for every master broker
  size:
    master: 1
    replica: 0

  master:
    brokerRole: ASYNC_MASTER
    jvmMemory: "-Xms1g -Xmx1g -Xmn256m "
    resources:
      limits:
        cpu: 4
        memory: 16Gi
      requests:
        cpu: 200m
        memory: 2Gi

  replica:
    jvmMemory: "-Xms1g -Xmx1g -Xmn256m "
    resources:
      limits:
        cpu: 4
        memory: 16Gi
      requests:
        cpu: 50m
        memory: 2Gi

  persistence:
    enabled: true
    size: 10Gi

  config:
    ## brokerClusterName brokerName brokerRole brokerId 由内置脚本自动生成
    deleteWhen: "04"
    fileReservedTime: "48"
    flushDiskType: "ASYNC_FLUSH"
    waitTimeMillsInSendQueue: "1000"
    #transientStorePoolEnable: "true"
    #transferMsgByHeap: "false"

  affinityOverride: {}
  tolerations: {}
  nodeSelector: {}

# Configuration for the nameserver
nameserver:
  # -- Number of replicaCount for nameserver
  replicaCount: 1

  resources:
    limits:
      cpu: 2
      memory: 6Gi
      ephemeral-storage: 8Gi
    requests:
      cpu: 100m
      memory: 2Gi
      ephemeral-storage: 1Gi
  
  persistence:
    enabled: false
    size: 10Gi

  affinityOverride: {}
  tolerations: {}
  nodeSelector: {}

# Configuration for the dashboard
dashboard:
  enabled: true
  replicaCount: 1
  image:
    repository: "apacherocketmq/rocketmq-dashboard"
    pullPolicy: IfNotPresent
    tag: "1.0.0"

  jvm:
    maxHeapSize: 256M

  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 20m
      memory: 512Mi

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,124.160.30.50
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local